{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LLVMError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/llvm\/llvmerror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/LLVM\/s5ErrorP","doc:\/\/LLVM\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error that occurred during a LLVM operation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LLVMError"}],"title":"LLVMError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:4LLVM9LLVMErrorV","modules":[{"name":"LLVM"}],"navigatorTitle":[{"kind":"identifier","text":"LLVMError"}]},"hierarchy":{"paths":[["doc:\/\/LLVM\/documentation\/LLVM"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/Error-Implementations"],"generated":true}],"references":{"doc://LLVM/documentation/LLVM/LLVMError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/llvm\/llvmerror\/error-implementations"},"doc://LLVM/documentation/LLVM":{"role":"collection","title":"LLVM","abstract":[],"identifier":"doc:\/\/LLVM\/documentation\/LLVM","kind":"symbol","type":"topic","url":"\/documentation\/llvm"},"doc://LLVM/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/LLVM\/s5ErrorP"},"doc://LLVM/documentation/LLVM/LLVMError/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A description of the error."}],"identifier":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/description","kind":"symbol","type":"topic","url":"\/documentation\/llvm\/llvmerror\/description"},"doc://LLVM/documentation/LLVM/LLVMError":{"role":"symbol","title":"LLVMError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LLVMError"}],"abstract":[{"type":"text","text":"An error that occurred during a LLVM operation."}],"identifier":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LLVMError"}],"url":"\/documentation\/llvm\/llvmerror"},"doc://LLVM/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/LLVM\/s8SendableP"}}}