{"variants":[{"paths":["\/documentation\/llvm\/llvmerror\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/localizedDescription"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"LLVM"}],"role":"collectionGroup","title":"Error Implementations"},"hierarchy":{"paths":[["doc:\/\/LLVM\/documentation\/LLVM","doc:\/\/LLVM\/documentation\/LLVM\/LLVMError"]]},"references":{"doc://LLVM/documentation/LLVM/LLVMError":{"role":"symbol","title":"LLVMError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LLVMError"}],"abstract":[{"type":"text","text":"An error that occurred during a LLVM operation."}],"identifier":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LLVMError"}],"url":"\/documentation\/llvm\/llvmerror"},"doc://LLVM/documentation/LLVM":{"role":"collection","title":"LLVM","abstract":[],"identifier":"doc:\/\/LLVM\/documentation\/LLVM","kind":"symbol","type":"topic","url":"\/documentation\/llvm"},"doc://LLVM/documentation/LLVM/LLVMError/localizedDescription":{"role":"symbol","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Retrieve the localized description for this error."}],"identifier":"doc:\/\/LLVM\/documentation\/LLVM\/LLVMError\/localizedDescription","kind":"symbol","type":"topic","url":"\/documentation\/llvm\/llvmerror\/localizeddescription"}}}